const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
export { escapeHTML };

const dateLabel = entry => entry.temporal?.display || entry.date || 'Undated';
const meta = entry => (entry.metadata?.threads || entry.threads || ['Unplaced']).map(t => `<span class="tag">${escapeHTML(t)}</span>`).join('');

export function shellView(entries) {
  return `<div class="shell"><nav class="rail" aria-label="Primary">
    <button class="nav-button is-active" data-route="home">Record</button><button class="nav-button" data-route="write">Say</button><button class="nav-button" data-route="drift">Drift</button><button class="nav-button" data-route="between">Between</button><button class="nav-button" data-route="library">Library</button><button class="nav-button" data-route="search">Search</button><button class="nav-button" data-route="places">Places</button>
  </nav><main class="main"><header class="top"><div class="brand">All I Say</div><div id="count" class="count">${entries.length} positions</div></header>
  ${homeView(entries)}${writeView()}${driftView()}${betweenView(entries)}<section id="library" class="panel"><div id="libraryMount"></div></section><section id="search" class="panel"><div id="searchMount"></div></section><section id="places" class="panel"><div id="placesMount"></div></section><section id="inspect" class="panel"><div id="inspectMount"></div></section></main></div>`;
}
export function homeView(entries) { const recent=[...entries].slice(0,6); return `<section id="home" class="panel is-active"><div class="hero"><h1 class="hero-title">All<br>I Say</h1><p class="hero-copy">What has just entered the record.</p></div><div class="record-actions"><button class="button-primary" data-route="write">Say something</button><button class="button-ghost" data-route="library">Enter the whole record</button></div><div class="section-head"><div class="eyebrow">Recent</div><div class="eyebrow">${recent.length} in sight</div></div><div id="feed" class="record">${feedView(recent)}</div></section>`; }
export function feedView(entries) { if (!entries.length) return '<p class="note">Nothing yet. Say something.</p>'; return entries.map((entry,index)=>`<article class="entry" data-entry-id="${escapeHTML(entry.id)}" tabindex="0"><div class="eyebrow">${escapeHTML(dateLabel(entry))}</div><blockquote class="entry-quote">${escapeHTML(entry.text ?? '[Artifact preserved; no canonical utterance text]')}</blockquote><div class="meta">${meta(entry)}<span class="tag">Kept</span></div></article>`).join(''); }
export function writeView(){return `<section id="write" class="panel"><div class="compose-wrap"><div class="eyebrow">Say</div><h2 class="big-title">What are you thinking?</h2><textarea id="entryText" class="compose-text" placeholder="No title required." aria-label="Your words"></textarea><label class="artifact-control">Attach an artifact<input id="artifactFile" type="file" accept="image/*,audio/*,.pdf" /></label><input id="artifactTranscription" class="artifact-transcription" placeholder="Optional reading of the artifact" aria-label="Artifact transcription" /><div class="compose-foot"><span class="small">Artifact, reading, and utterance stay distinct.</span><button id="saveEntry" class="button-primary">Keep</button></div></div></section>`; }
export function driftView(){return `<section id="drift" class="panel"><div class="drift-card"><div><div class="eyebrow">Drift · one thing you said</div><div id="driftQuote" class="drift-quote"></div></div><div class="drift-actions"><div id="driftMeta" class="small"></div><div class="drift-buttons"><button id="driftInspect" class="button-ghost" hidden>See where this was</button><button id="newDrift" class="button-ghost">Another</button></div></div></div></section>`; }
export function betweenView(){return `<section id="between" class="panel"><div class="eyebrow">Between</div><h2 class="big-title">Put two positions<br>in sight.</h2><div class="between-grid"><select id="betweenA" class="picker"></select><select id="betweenB" class="picker"></select></div><div id="bridge" class="bridge"></div></section>`; }
export function optionView(entries,selected=0){return entries.map((e,i)=>`<option value="${escapeHTML(e.id)}" ${i===selected?'selected':''}>${escapeHTML(e.text ?? '[Artifact only]').slice(0,88)}</option>`).join('');}
export function bridgeView(a,b,relations=[]){if(!a||!b)return '<p class="note">Choose two utterances to place them between.</p>';const position=e=>`<div class="position" data-entry-id="${escapeHTML(e.id)}"><div class="eyebrow">${escapeHTML(dateLabel(e))}</div><blockquote class="position-quote">${escapeHTML(e.text ?? '[Artifact only]')}</blockquote></div>`;const declared=relations.length?`<div class="declared-relations"><div class="eyebrow">Relations you recorded</div>${relations.map(r=>`<span class="tag">${escapeHTML(r.type)}</span>`).join('')}</div>`:'';return `${position(a)}<div class="between-line"><span>Between</span></div>${position(b)}${declared}`;}
