import { escapeHTML } from './views.js';

export function inspectView(inspection) {
  if (!inspection) return '<section id="inspect" class="panel"><p class="note">This utterance could not be found.</p><button class="button-ghost" data-route="home">Back to Record</button></section>';
  const { utterance, artifacts, transcriptions } = inspection;
  const artifactMarkup = artifacts.length ? artifacts.map(artifact => `<div class="inspect-item"><div class="eyebrow">${escapeHTML(artifact.kind)} · ${escapeHTML(artifact.mimeType)}</div><div class="small">${escapeHTML(artifact.capturedAt || 'Capture time unknown')}</div></div>`).join('') : '<p class="small">No artifact attached.</p>';
  const transcriptionMarkup = transcriptions.length ? transcriptions.map(item => `<div class="inspect-item"><div class="inspect-reading">${escapeHTML(item.text)}</div><div class="meta"><span class="tag">${escapeHTML(item.provenance?.origin || 'unknown')}</span><span class="tag">${escapeHTML(item.attestation?.state || 'unreviewed')}</span><span class="tag">${escapeHTML(item.createdAt)}</span></div></div>`).join('') : '<p class="small">No transcription recorded.</p>';
  return `<section id="inspect" class="panel"><button class="button-ghost" data-route="home">← Record</button><div class="inspect-head"><div class="eyebrow">Utterance</div><blockquote class="inspect-quote">${escapeHTML(utterance.text ?? '[Awaiting transcription]')}</blockquote><div class="meta"><span class="tag">${escapeHTML(utterance.displayDate || 'Undated')}</span><span class="tag">${escapeHTML(utterance.metadata?.status || 'unknown')}</span><span class="tag">${escapeHTML(utterance.source?.type || 'unknown')}</span></div></div><div class="inspect-section"><h2>Artifacts</h2>${artifactMarkup}</div><div class="inspect-section"><h2>Transcription history</h2>${transcriptionMarkup}</div><div class="inspect-section"><h2>Annotations and interpretations</h2><p class="small">No annotations or interpretations are stored for this utterance yet.</p></div><div class="inspect-section"><h2>Relations</h2><p class="small">No relations are stored for this utterance yet.</p></div></section>`;
}
